name: location_marker_example
description: Example of FlutterMapLocationMarkerPlugin
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

# flutter_joystick,flutter_map,geolocator,latlong2
dependencies:
  flutter:
    sdk: flutter
  flutter_compass:
    git: https://github.com/Hasuki69/flutter_compass.git
  flutter_joystick: ^0.2.1
  flutter_map: ^7.0.2
  flutter_map_location_marker:
    path: ../
  geolocator: ^13.0.1
  latlong2: ^0.9.1

# lint
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true
