name: flutter_map_location_marker
description: A flutter map plugin for displaying device current location.
version: 9.0.0
repository: https://github.com/tlserver/flutter_map_location_marker

publish_to: none

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

# flutter_map,geolocator,latlong2
dependencies:
  flutter:
    sdk: flutter
  flutter_compass:
    git: https://github.com/Hasuki69/flutter_compass.git
  flutter_map: ^7.0.2
  geolocator: ^13.0.1
  latlong2: ^0.9.1

# flutter_lints,lint
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
